#!/bin/bash

files=$(ls ~/.dotfiles/keyd/keyd/ | grep \\.)

cd ~/.dotfiles/keyd/keyd/

for file in $files; do
    newname=$(echo $file | sed "s/\.[^\.]*$//")
    mv $file $newname
done

if [ "$1" == "" ]; then
    mv keyd keyd.conf
else
    mv $1 $1".conf"
fi


cd ~/.dotfiles/ && sudo stow -R keyd --target=/etc/
sudo keyd reload
