[mgr]
ratio = [1,2,5]

[plugin]
pre_exit = "yazi -p"

[preview]
max_width = 800
wrap = "yes"

[opener]
qpdfview = [
{ run = 'qpdfview "$@"', desc = "QPDFView" },
]
zathura = [
{ run = 'zathura "$@"', desc = "Zathura" },
]
ristretto = [
{ run = 'ristretto "$@"', desc = "Ristretto" },
]
nautilus = [
{ run = 'nautilus %S', desc = "View in Thunar" },
]

[open]
prepend_rules = [
{ url = "*.pdf", use = "qpdfview" },
{ url = "*.pdf", use = "zathura" },
{ url = "*.png", use = "ristretto" },
{ url = "*.jpg", use = "ristretto" },
]
