color0 #29141b
color1 #a14361
color2 #e4678f
color3 #d6725c
color4 #ad66cc
color5 #ec93af
color6 #e9a596
color7 #f3f2f2
color8 #756167
color9 #a14361
color10 #e4678f
color11 #d6725c
color12 #ad66cc
color13 #ec93af
color14 #e9a596
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #29141b
background            #29141b
foreground            #f3f2f2
selection_foreground  #b6afb1
selection_background  #371b24
active_border_color   #e4678f
inactive_border_color #371b24
url_color             #e4678f

active_tab_foreground   #25181c
active_tab_background   #e4678f
inactive_tab_foreground #b6afb1
inactive_tab_background #371b24
cursor_trail_color      #b6afb1
