color0 #161d3b
color1 #fd4663
color2 #677ee4
color3 #9069e4
color4 #b966cc
color5 #93a3ec
color6 #b196e9
color7 #f2f2f3
color8 #606470
color9 #fd4663
color10 #677ee4
color11 #9069e4
color12 #b966cc
color13 #93a3ec
color14 #b196e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #11162c
background            #11162c
foreground            #f2f2f3
selection_foreground  #afb0b6
selection_background  #161d3b
active_border_color   #677ee4
inactive_border_color #161d3b
url_color             #677ee4

active_tab_foreground   #181b25
active_tab_background   #677ee4
inactive_tab_foreground #afb0b6
inactive_tab_background #161d3b
cursor_trail_color      #afb0b6
