color0 #081e49
color1 #fd4663
color2 #4d89ff
color3 #5cd679
color4 #bc40ff
color5 #80aaff
color6 #96e9aa
color7 #f2f2f3
color8 #5f656f
color9 #fd4663
color10 #4d89ff
color11 #5cd679
color12 #bc40ff
color13 #80aaff
color14 #96e9aa
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #03163a
background            #03163a
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #081e49
active_border_color   #4d89ff
inactive_border_color #081e49
url_color             #4d89ff

active_tab_foreground   #181d25
active_tab_background   #4d89ff
inactive_tab_foreground #afb1b6
inactive_tab_background #081e49
cursor_trail_color      #afb1b6
