color0 #222830
color1 #fd4663
color2 #67a0e4
color3 #7776f2
color4 #a46cd2
color5 #93bbec
color6 #9996e9
color7 #f2f2f3
color8 #616971
color9 #fd4663
color10 #67a0e4
color11 #7776f2
color12 #a46cd2
color13 #93bbec
color14 #9996e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #191e24
background            #191e24
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #222830
active_border_color   #67a0e4
inactive_border_color #222830
url_color             #67a0e4

active_tab_foreground   #181e25
active_tab_background   #67a0e4
inactive_tab_foreground #afb2b6
inactive_tab_background #222830
cursor_trail_color      #afb2b6
